#ifndef KERNEL_H
#define KERNEL_H

#define INIT_BG VGA_BG_BLACK
#define OK VGA_ENTRY_COLOR(INIT_BG, VGA_FG_LIGHT_GREEN)
#define TAG VGA_ENTRY_COLOR(INIT_BG, VGA_FG_LIGHT_GREY)
#define MSG VGA_ENTRY_COLOR(INIT_BG, VGA_FG_WHITE)
#define SHELL_BG VGA_BG_BLACK
#define SHELL_FG VGA_FG_WHITE

#endif
